/*
 * Copyright 2024 Marcus Madland. All rights reserved.
 * License: https://github.com/marcusmadland/max/blob/mainICENSE
 */

#ifndef MAX_CONFIG_H_HEADER_GUARD
#define MAX_CONFIG_H_HEADER_GUARD

#include <bx/bx.h> // bx::isPowerOf2

// # Configuration options for max.
//
// Any of `MAX_CONFIG_*` options that's inside `#ifndef` block can be configured externally
// via compiler options.
//
// When selecting rendering backends select all backends you want to include in the build.

#ifndef BX_CONFIG_DEBUG
#	error "BX_CONFIG_DEBUG must be defined in build script!"
#endif // BX_CONFIG_DEBUG

#if !defined(MAX_CONFIG_PHYSICS_JOLT) 

#	ifndef MAX_CONFIG_PHYSICS_JOLT
#		define MAX_CONFIG_PHYSICS_JOLT (0 \
					|| BX_PLATFORM_ANDROID    \
					|| BX_PLATFORM_LINUX      \
					|| BX_PLATFORM_WINDOWS    \
					|| BX_PLATFORM_NX         \
					|| BX_PLATFORM_OSX        \
					? 1 : 0)
#	endif // MAX_CONFIG_PHYSICS_JOLT

#else

#	ifndef MAX_CONFIG_PHYSICS_JOLT
#		define MAX_CONFIG_PHYSICS_JOLT 0
#	endif // MAX_CONFIG_PHYSICS_JOLT

#endif // !defined...

#if !defined(MAX_CONFIG_RENDERER_AGC)        \
 && !defined(MAX_CONFIG_RENDERER_DIRECT3D11) \
 && !defined(MAX_CONFIG_RENDERER_DIRECT3D12) \
 && !defined(MAX_CONFIG_RENDERER_GNM)        \
 && !defined(MAX_CONFIG_RENDERER_METAL)      \
 && !defined(MAX_CONFIG_RENDERER_NVN)        \
 && !defined(MAX_CONFIG_RENDERER_OPENGL)     \
 && !defined(MAX_CONFIG_RENDERER_OPENGLES)   \
 && !defined(MAX_CONFIG_RENDERER_VULKAN)

#	ifndef MAX_CONFIG_RENDERER_AGC
#		define MAX_CONFIG_RENDERER_AGC (0 \
					|| BX_PLATFORM_PS5     \
					? 1 : 0)
#	endif // MAX_CONFIG_RENDERER_AGC

#	ifndef MAX_CONFIG_RENDERER_DIRECT3D11
#		define MAX_CONFIG_RENDERER_DIRECT3D11 (0 \
					|| BX_PLATFORM_LINUX          \
					|| BX_PLATFORM_WINDOWS        \
					|| BX_PLATFORM_WINRT          \
					|| BX_PLATFORM_XBOXONE        \
					? 1 : 0)
#	endif // MAX_CONFIG_RENDERER_DIRECT3D11

#	ifndef MAX_CONFIG_RENDERER_DIRECT3D12
#		define MAX_CONFIG_RENDERER_DIRECT3D12 (0 \
					|| BX_PLATFORM_LINUX          \
					|| BX_PLATFORM_WINDOWS        \
					|| BX_PLATFORM_WINRT          \
					|| BX_PLATFORM_XBOXONE        \
					? 1 : 0)
#	endif // MAX_CONFIG_RENDERER_DIRECT3D12

#	ifndef MAX_CONFIG_RENDERER_GNM
#		define MAX_CONFIG_RENDERER_GNM (0 \
					|| BX_PLATFORM_PS4     \
					? 1 : 0)
#	endif // MAX_CONFIG_RENDERER_GNM

#	ifndef MAX_CONFIG_RENDERER_METAL
#		define MAX_CONFIG_RENDERER_METAL (0 \
					|| BX_PLATFORM_IOS       \
					|| BX_PLATFORM_OSX       \
					|| BX_PLATFORM_VISIONOS \
					? 1 : 0)
#	endif // MAX_CONFIG_RENDERER_METAL

#	ifndef MAX_CONFIG_RENDERER_NVN
#		define MAX_CONFIG_RENDERER_NVN (0 \
					|| BX_PLATFORM_NX      \
					? 1 : 0)
#	endif // MAX_CONFIG_RENDERER_NVN

#	ifndef MAX_CONFIG_RENDERER_OPENGL_MIN_VERSION
#		define MAX_CONFIG_RENDERER_OPENGL_MIN_VERSION 1
#	endif // MAX_CONFIG_RENDERER_OPENGL_MIN_VERSION

#	ifndef MAX_CONFIG_RENDERER_OPENGL
#		define MAX_CONFIG_RENDERER_OPENGL (0 \
					|| BX_PLATFORM_LINUX      \
					|| BX_PLATFORM_WINDOWS    \
					? MAX_CONFIG_RENDERER_OPENGL_MIN_VERSION : 0)
#	endif // MAX_CONFIG_RENDERER_OPENGL

#	ifndef MAX_CONFIG_RENDERER_OPENGLES_MIN_VERSION
#		define MAX_CONFIG_RENDERER_OPENGLES_MIN_VERSION (0 \
					|| BX_PLATFORM_ANDROID                  \
					? 30 : 1)
#	endif // MAX_CONFIG_RENDERER_OPENGLES_MIN_VERSION

#	ifndef MAX_CONFIG_RENDERER_OPENGLES
#		define MAX_CONFIG_RENDERER_OPENGLES (0 \
					|| BX_PLATFORM_ANDROID      \
					|| BX_PLATFORM_EMSCRIPTEN   \
					|| BX_PLATFORM_RPI          \
					|| BX_PLATFORM_NX           \
					? MAX_CONFIG_RENDERER_OPENGLES_MIN_VERSION : 0)
#	endif // MAX_CONFIG_RENDERER_OPENGLES

#	ifndef MAX_CONFIG_RENDERER_VULKAN
#		define MAX_CONFIG_RENDERER_VULKAN (0 \
					|| BX_PLATFORM_ANDROID    \
					|| BX_PLATFORM_LINUX      \
					|| BX_PLATFORM_WINDOWS    \
					|| BX_PLATFORM_NX         \
					|| BX_PLATFORM_OSX        \
					? 1 : 0)
#	endif // MAX_CONFIG_RENDERER_VULKAN

#else
#	ifndef MAX_CONFIG_RENDERER_AGC
#		define MAX_CONFIG_RENDERER_AGC 0
#	endif // MAX_CONFIG_RENDERER_AGC

#	ifndef MAX_CONFIG_RENDERER_DIRECT3D11
#		define MAX_CONFIG_RENDERER_DIRECT3D11 0
#	endif // MAX_CONFIG_RENDERER_DIRECT3D11

#	ifndef MAX_CONFIG_RENDERER_DIRECT3D12
#		define MAX_CONFIG_RENDERER_DIRECT3D12 0
#	endif // MAX_CONFIG_RENDERER_DIRECT3D12

#	ifndef MAX_CONFIG_RENDERER_GNM
#		define MAX_CONFIG_RENDERER_GNM 0
#	endif // MAX_CONFIG_RENDERER_GNM

#	ifndef MAX_CONFIG_RENDERER_METAL
#		define MAX_CONFIG_RENDERER_METAL 0
#	endif // MAX_CONFIG_RENDERER_METAL

#	ifndef MAX_CONFIG_RENDERER_NVN
#		define MAX_CONFIG_RENDERER_NVN 0
#	endif // MAX_CONFIG_RENDERER_NVN

#	ifndef MAX_CONFIG_RENDERER_OPENGL
#		define MAX_CONFIG_RENDERER_OPENGL 0
#	endif // MAX_CONFIG_RENDERER_OPENGL

#	ifndef MAX_CONFIG_RENDERER_OPENGLES
#		define MAX_CONFIG_RENDERER_OPENGLES 0
#	endif // MAX_CONFIG_RENDERER_OPENGLES

#	ifndef MAX_CONFIG_RENDERER_VULKAN
#		define MAX_CONFIG_RENDERER_VULKAN 0
#	endif // MAX_CONFIG_RENDERER_VULKAN
#endif // !defined...

#if MAX_CONFIG_RENDERER_OPENGL && MAX_CONFIG_RENDERER_OPENGL < 21
#	undef MAX_CONFIG_RENDERER_OPENGL
#	define MAX_CONFIG_RENDERER_OPENGL 21
#endif // MAX_CONFIG_RENDERER_OPENGL && MAX_CONFIG_RENDERER_OPENGL < 21

#if MAX_CONFIG_RENDERER_OPENGLES && MAX_CONFIG_RENDERER_OPENGLES < 20
#	undef MAX_CONFIG_RENDERER_OPENGLES
#	define MAX_CONFIG_RENDERER_OPENGLES 20
#endif // MAX_CONFIG_RENDERER_OPENGLES && MAX_CONFIG_RENDERER_OPENGLES < 20

#if MAX_CONFIG_RENDERER_OPENGL && MAX_CONFIG_RENDERER_OPENGLES
#	error "Can't define both MAX_CONFIG_RENDERER_OPENGL and MAX_CONFIG_RENDERER_OPENGLES"
#endif // MAX_CONFIG_RENDERER_OPENGL && MAX_CONFIG_RENDERER_OPENGLES

/// Enable use of extensions.
#ifndef MAX_CONFIG_RENDERER_USE_EXTENSIONS
#	define MAX_CONFIG_RENDERER_USE_EXTENSIONS 1
#endif // MAX_CONFIG_RENDERER_USE_EXTENSIONS

#ifndef MAX_CONFIG_RENDERER_DIRECT3D11_USE_STAGING_BUFFER
#	define MAX_CONFIG_RENDERER_DIRECT3D11_USE_STAGING_BUFFER 0
#endif // MAX_CONFIG_RENDERER_DIRECT3D11_USE_STAGING_BUFFER

/// Enable use of tinystl.
#ifndef MAX_CONFIG_USE_TINYSTL
#	define MAX_CONFIG_USE_TINYSTL 1
#endif // MAX_CONFIG_USE_TINYSTL

#ifndef MAX_CONFIG_IMPLEMENT_DEFAULT_ALLOCATOR
#	define MAX_CONFIG_IMPLEMENT_DEFAULT_ALLOCATOR 1
#endif // MAX_CONFIG_IMPLEMENT_DEFAULT_ALLOCATOR

#ifndef MAX_CONFIG_PROFILER
#	define MAX_CONFIG_PROFILER 0
#endif // MAX_CONFIG_PROFILER

#ifndef MAX_CONFIG_USE_NOOP
#	define MAX_CONFIG_USE_NOOP 0
#endif // MAX_CONFIG_USE_NOOP

#ifndef MAX_CONFIG_USE_SDL
#	define MAX_CONFIG_USE_SDL 0
#endif // MAX_CONFIG_USE_SDL

#ifndef MAX_CONFIG_USE_GLFW
#	define MAX_CONFIG_USE_GLFW 0
#endif // MAX_CONFIG_USE_GLFW

#ifndef MAX_CONFIG_USE_WAYLAND
#	define MAX_CONFIG_USE_WAYLAND 0
#endif // MAX_CONFIG_USE_WAYLAND

#if !defined(MAX_CONFIG_USE_NATIVE) \
	&& !MAX_CONFIG_USE_NOOP \
	&& !MAX_CONFIG_USE_SDL \
	&& !MAX_CONFIG_USE_GLFW
#	define MAX_CONFIG_USE_NATIVE 1
#else
#	define MAX_CONFIG_USE_NATIVE 0
#endif // ...

#ifndef MAX_CONFIG_MAX_WINDOWS
#	define MAX_CONFIG_MAX_WINDOWS 8
#endif // MAX_CONFIG_MAX_WINDOWS

#ifndef MAX_CONFIG_MAX_GAMEPADS
#	define MAX_CONFIG_MAX_GAMEPADS 4
#endif // MAX_CONFIG_MAX_GAMEPADS

/// Debug text maximum scale factor.
#ifndef MAX_CONFIG_DEBUG_TEXT_MAX_SCALE
#	define MAX_CONFIG_DEBUG_TEXT_MAX_SCALE 4
#endif // MAX_CONFIG_DEBUG_TEXT_MAX_SCALE

/// Enable nVidia PerfHUD integration.
#ifndef MAX_CONFIG_DEBUG_PERFHUD
#	define MAX_CONFIG_DEBUG_PERFHUD 0
#endif // MAX_CONFIG_DEBUG_NVPERFHUD

/// Enable annotation for graphics debuggers.
#ifndef MAX_CONFIG_DEBUG_ANNOTATION
#	define MAX_CONFIG_DEBUG_ANNOTATION MAX_CONFIG_DEBUG
#endif // MAX_CONFIG_DEBUG_ANNOTATION

/// Enable DX11 object names.
#ifndef MAX_CONFIG_DEBUG_OBJECT_NAME
#	define MAX_CONFIG_DEBUG_OBJECT_NAME MAX_CONFIG_DEBUG_ANNOTATION
#endif // MAX_CONFIG_DEBUG_OBJECT_NAME

/// Enable uniform debug checks.
#ifndef MAX_CONFIG_DEBUG_UNIFORM
#	define MAX_CONFIG_DEBUG_UNIFORM MAX_CONFIG_DEBUG
#endif // MAX_CONFIG_DEBUG_UNIFORM

/// Enable occlusion debug checks.
#ifndef MAX_CONFIG_DEBUG_OCCLUSION
#	define MAX_CONFIG_DEBUG_OCCLUSION MAX_CONFIG_DEBUG
#endif // MAX_CONFIG_DEBUG_OCCLUSION

#ifndef MAX_CONFIG_MULTITHREADED
#	define MAX_CONFIG_MULTITHREADED ( (0 == BX_PLATFORM_EMSCRIPTEN) ? 1 : 0)
#endif // MAX_CONFIG_MULTITHREADED

#ifndef MAX_CONFIG_MAX_DRAW_CALLS
#	define MAX_CONFIG_MAX_DRAW_CALLS ( (64<<10)-1)
#endif // MAX_CONFIG_MAX_DRAW_CALLS

#ifndef MAX_CONFIG_MAX_BLIT_ITEMS
#	define MAX_CONFIG_MAX_BLIT_ITEMS (1<<10)
#endif // MAX_CONFIG_MAX_BLIT_ITEMS

#ifndef MAX_CONFIG_MAX_MATRIX_CACHE
#	define MAX_CONFIG_MAX_MATRIX_CACHE (MAX_CONFIG_MAX_DRAW_CALLS+1)
#endif // MAX_CONFIG_MAX_MATRIX_CACHE

#ifndef MAX_CONFIG_MAX_RECT_CACHE
#	define MAX_CONFIG_MAX_RECT_CACHE (4<<10)
#endif //  MAX_CONFIG_MAX_RECT_CACHE

#ifndef MAX_CONFIG_SORT_KEY_NUM_BITS_DEPTH
#	define MAX_CONFIG_SORT_KEY_NUM_BITS_DEPTH 32
#endif // MAX_CONFIG_SORT_KEY_NUM_BITS_DEPTH

#ifndef MAX_CONFIG_SORT_KEY_NUM_BITS_SEQ
#	define MAX_CONFIG_SORT_KEY_NUM_BITS_SEQ 20
#endif // MAX_CONFIG_SORT_KEY_NUM_BITS_SEQ

#ifndef MAX_CONFIG_SORT_KEY_NUM_BITS_PROGRAM
#	define MAX_CONFIG_SORT_KEY_NUM_BITS_PROGRAM 9
#endif // MAX_CONFIG_SORT_KEY_NUM_BITS_PROGRAM

#ifndef MAX_CONFIG_MAX_BODIES
#	define MAX_CONFIG_MAX_BODIES 1024
#endif // MAX_CONFIG_MAX_BODIES

#ifndef MAX_CONFIG_MAX_BODY_PAIRS
#	define MAX_CONFIG_MAX_BODY_PAIRS 1024
#endif // MAX_CONFIG_MAX_BODY_PAIRS

#ifndef MAX_CONFIG_MAX_CONTACT_CONSTRAINTS
#	define MAX_CONFIG_MAX_CONTACT_CONSTRAINTS 1024
#endif // MAX_CONFIG_MAX_CONTACT_CONSTRAINTS

// Cannot be configured via compiler options.
#define MAX_CONFIG_MAX_PROGRAMS (1<<MAX_CONFIG_SORT_KEY_NUM_BITS_PROGRAM)
BX_STATIC_ASSERT(bx::isPowerOf2(MAX_CONFIG_MAX_PROGRAMS), "MAX_CONFIG_MAX_PROGRAMS must be power of 2.");

#ifndef MAX_CONFIG_MAX_VIEWS
#	define MAX_CONFIG_MAX_VIEWS 256
#endif // MAX_CONFIG_MAX_VIEWS
BX_STATIC_ASSERT(bx::isPowerOf2(MAX_CONFIG_MAX_VIEWS), "MAX_CONFIG_MAX_VIEWS must be power of 2.");

#define MAX_CONFIG_MAX_VIEW_NAME_RESERVED 6

#ifndef MAX_CONFIG_MAX_VIEW_NAME
#	define MAX_CONFIG_MAX_VIEW_NAME 256
#endif // MAX_CONFIG_MAX_VIEW_NAME

#ifndef MAX_CONFIG_MAX_VERTEX_LAYOUTS
#	define MAX_CONFIG_MAX_VERTEX_LAYOUTS 64
#endif // MAX_CONFIG_MAX_VERTEX_LAYOUTS

#ifndef MAX_CONFIG_MAX_INDEX_BUFFERS
#	define MAX_CONFIG_MAX_INDEX_BUFFERS (4<<10)
#endif // MAX_CONFIG_MAX_INDEX_BUFFERS

#ifndef MAX_CONFIG_MAX_VERTEX_BUFFERS
#	define MAX_CONFIG_MAX_VERTEX_BUFFERS (4<<10)
#endif // MAX_CONFIG_MAX_VERTEX_BUFFERS

#ifndef MAX_CONFIG_MAX_VERTEX_STREAMS
#	define MAX_CONFIG_MAX_VERTEX_STREAMS 4
#endif // MAX_CONFIG_MAX_VERTEX_STREAMS

#ifndef MAX_CONFIG_MAX_DYNAMIC_INDEX_BUFFERS
#	define MAX_CONFIG_MAX_DYNAMIC_INDEX_BUFFERS (4<<10)
#endif // MAX_CONFIG_MAX_DYNAMIC_INDEX_BUFFERS

#ifndef MAX_CONFIG_MAX_DYNAMIC_VERTEX_BUFFERS
#	define MAX_CONFIG_MAX_DYNAMIC_VERTEX_BUFFERS (4<<10)
#endif // MAX_CONFIG_MAX_DYNAMIC_VERTEX_BUFFERS

#ifndef MAX_CONFIG_DYNAMIC_INDEX_BUFFER_SIZE
#	define MAX_CONFIG_DYNAMIC_INDEX_BUFFER_SIZE (1<<20)
#endif // MAX_CONFIG_DYNAMIC_INDEX_BUFFER_SIZE

#ifndef MAX_CONFIG_DYNAMIC_VERTEX_BUFFER_SIZE
#	define MAX_CONFIG_DYNAMIC_VERTEX_BUFFER_SIZE (3<<20)
#endif // MAX_CONFIG_DYNAMIC_VERTEX_BUFFER_SIZE

#ifndef MAX_CONFIG_MAX_SHADERS
#	define MAX_CONFIG_MAX_SHADERS 512
#endif // MAX_CONFIG_MAX_FRAGMENT_SHADERS

#ifndef MAX_CONFIG_MAX_TEXTURES
#	define MAX_CONFIG_MAX_TEXTURES (4<<10)
#endif // MAX_CONFIG_MAX_TEXTURES

#ifndef MAX_CONFIG_MAX_TEXTURE_SAMPLERS
#	define MAX_CONFIG_MAX_TEXTURE_SAMPLERS 16
#endif // MAX_CONFIG_MAX_TEXTURE_SAMPLERS

#ifndef MAX_CONFIG_MAX_FRAME_BUFFERS
#	define MAX_CONFIG_MAX_FRAME_BUFFERS 128
#endif // MAX_CONFIG_MAX_FRAME_BUFFERS

#ifndef MAX_CONFIG_MAX_FRAME_BUFFER_ATTACHMENTS
#	define MAX_CONFIG_MAX_FRAME_BUFFER_ATTACHMENTS 8
#endif // MAX_CONFIG_MAX_FRAME_BUFFER_ATTACHMENTS

#ifndef MAX_CONFIG_MAX_UNIFORMS
#	define MAX_CONFIG_MAX_UNIFORMS 512
#endif // MAX_CONFIG_MAX_UNIFORMS

#ifndef MAX_CONFIG_MAX_UNIFORMS_PER_MATERIAL
#	define MAX_CONFIG_MAX_UNIFORMS_PER_MATERIAL 128
#endif // MAX_CONFIG_MAX_UNIFORMS_PER_MATERIAL

#ifndef MAX_CONFIG_MAX_MATERIALS
#	define MAX_CONFIG_MAX_MATERIALS 256
#endif // MAX_CONFIG_MAX_MATERIALS

#ifndef MAX_CONFIG_MAX_MESHES
#	define MAX_CONFIG_MAX_MESHES 1024
#endif // MAX_CONFIG_MAX_MESHES

#ifndef MAX_CONFIG_MAX_MESH_GROUPS
#	define MAX_CONFIG_MAX_MESH_GROUPS 124
#endif // MAX_CONFIG_MAX_MESH_GROUPS

#ifndef MAX_CONFIG_MAX_DYNAMIC_MESHES
#	define MAX_CONFIG_MAX_DYNAMIC_MESHES 1024
#endif // MAX_CONFIG_MAX_DYNAMIC_MESHES

#ifndef MAX_CONFIG_MAX_DYNAMIC_MESH_GROUPS
#	define MAX_CONFIG_MAX_DYNAMIC_MESH_GROUPS 124
#endif // MAX_CONFIG_MAX_DYNAMIC_MESH_GROUPS

#ifndef MAX_CONFIG_MAX_COMPONENTS
#	define MAX_CONFIG_MAX_COMPONENTS 512
#endif // MAX_CONFIG_MAX_COMPONENTS

#ifndef MAX_CONFIG_MAX_COMPONENTS_TYPES
#	define MAX_CONFIG_MAX_COMPONENTS_TYPES 64
#endif // MAX_CONFIG_MAX_COMPONENTS_TYPES

#ifndef MAX_CONFIG_MAX_ENTITIES_PER_COMPONENT_TYPE
#	define MAX_CONFIG_MAX_ENTITIES_PER_COMPONENT_TYPE 64
#endif // MAX_CONFIG_MAX_ENTITIES_PER_COMPONENT_TYPE

#ifndef MAX_CONFIG_MAX_COMPONENTS_PER_ENTITY
#	define MAX_CONFIG_MAX_COMPONENTS_PER_ENTITY 64
#endif // MAX_CONFIG_MAX_COMPONENTS_PER_ENTITY

#ifndef MAX_CONFIG_MAX_ENTITIES
#	define MAX_CONFIG_MAX_ENTITIES 256
#endif // MAX_CONFIG_MAX_ENTITIES

#ifndef MAX_CONFIG_MAX_OCCLUSION_QUERIES
#	define MAX_CONFIG_MAX_OCCLUSION_QUERIES 256
#endif // MAX_CONFIG_MAX_OCCLUSION_QUERIES

#ifndef MAX_CONFIG_MIN_RESOURCE_COMMAND_BUFFER_SIZE
#	define MAX_CONFIG_MIN_RESOURCE_COMMAND_BUFFER_SIZE (64<<10)
#endif // MAX_CONFIG_MIN_RESOURCE_COMMAND_BUFFER_SIZE

#ifndef MAX_CONFIG_TRANSIENT_VERTEX_BUFFER_SIZE
#	define MAX_CONFIG_TRANSIENT_VERTEX_BUFFER_SIZE (6<<20)
#endif // MAX_CONFIG_TRANSIENT_VERTEX_BUFFER_SIZE

#ifndef MAX_CONFIG_TRANSIENT_INDEX_BUFFER_SIZE
#	define MAX_CONFIG_TRANSIENT_INDEX_BUFFER_SIZE (2<<20)
#endif // MAX_CONFIG_TRANSIENT_INDEX_BUFFER_SIZE

#ifndef MAX_CONFIG_PER_FRAME_SCRATCH_STAGING_BUFFER_SIZE
/// Amount of scratch buffer size (per in-flight frame) that will be reserved
/// for staging data for copying to the device (such as vertex buffer data,
/// texture data, etc). This buffer will be used instead of allocating memory
/// on device separately for every data copy.
/// Note: Currently only used by the Vulkan backend.
#   define MAX_CONFIG_PER_FRAME_SCRATCH_STAGING_BUFFER_SIZE (32<<20)
#endif

#ifndef MAX_CONFIG_MAX_STAGING_SIZE_FOR_SCRACH_BUFFER
/// The threshold of data size above which the staging scratch buffer will
/// not be used, but instead a separate device memory allocation will take
/// place to stage the data for copying to device.
#   define MAX_CONFIG_MAX_STAGING_SIZE_FOR_SCRACH_BUFFER (16 << 20)
#endif

#ifndef MAX_CONFIG_MAX_INSTANCE_DATA_COUNT
#	define MAX_CONFIG_MAX_INSTANCE_DATA_COUNT 5
#endif // MAX_CONFIG_MAX_INSTANCE_DATA_COUNT

#ifndef MAX_CONFIG_MAX_COLOR_PALETTE
#	define MAX_CONFIG_MAX_COLOR_PALETTE 16
#endif // MAX_CONFIG_MAX_COLOR_PALETTE

#define MAX_CONFIG_DRAW_INDIRECT_STRIDE 32

#ifndef MAX_CONFIG_PROFILER
#	define MAX_CONFIG_PROFILER 0
#endif // MAX_CONFIG_PROFILER

#ifndef MAX_CONFIG_RENDERDOC_LOG_FILEPATH
#	define MAX_CONFIG_RENDERDOC_LOG_FILEPATH "temp/max"
#endif // MAX_CONFIG_RENDERDOC_LOG_FILEPATH

#ifndef MAX_CONFIG_RENDERDOC_CAPTURE_KEYS
#	define MAX_CONFIG_RENDERDOC_CAPTURE_KEYS { eRENDERDOC_Key_F11 }
#endif // MAX_CONFIG_RENDERDOC_CAPTURE_KEYS

#ifndef MAX_CONFIG_API_SEMAPHORE_TIMEOUT
#	define MAX_CONFIG_API_SEMAPHORE_TIMEOUT (5000)
#endif // MAX_CONFIG_API_SEMAPHORE_TIMEOUT

#ifndef MAX_CONFIG_MIP_LOD_BIAS
#	define MAX_CONFIG_MIP_LOD_BIAS 0
#endif // MAX_CONFIG_MIP_LOD_BIAS

#ifndef MAX_CONFIG_DEFAULT_MAX_ENCODERS
#	define MAX_CONFIG_DEFAULT_MAX_ENCODERS ( (0 != MAX_CONFIG_MULTITHREADED) ? 8 : 1)
#endif // MAX_CONFIG_DEFAULT_MAX_ENCODERS

#ifndef MAX_CONFIG_MAX_BACK_BUFFERS
#	define MAX_CONFIG_MAX_BACK_BUFFERS 4
#endif // MAX_CONFIG_MAX_BACK_BUFFERS

#ifndef MAX_CONFIG_MAX_FRAME_LATENCY
#	define MAX_CONFIG_MAX_FRAME_LATENCY 3
#endif // MAX_CONFIG_MAX_FRAME_LATENCY

#ifndef MAX_CONFIG_PREFER_DISCRETE_GPU
// On laptops with integrated and discrete GPU, prefer selection of discrete GPU.
// nVidia and AMD, on Windows only.
#	define MAX_CONFIG_PREFER_DISCRETE_GPU BX_PLATFORM_WINDOWS
#endif // MAX_CONFIG_PREFER_DISCRETE_GPU

#ifndef MAX_CONFIG_MAX_SCREENSHOTS
#	define MAX_CONFIG_MAX_SCREENSHOTS 4
#endif // MAX_CONFIG_MAX_SCREENSHOTS

#ifndef MAX_CONFIG_ENCODER_API_ONLY
#	define MAX_CONFIG_ENCODER_API_ONLY 0
#endif // MAX_CONFIG_ENCODER_API_ONLY

#endif // MAX_CONFIG_H_HEADER_GUARD
